### ISSUE TITLE
options

### ISSUE THREAD

**Issue by superon** [jusipat/CastleBlocks#11]
cool! can we have more options?
i'd like to change the "activation block" from stone variant to brick variant and the trowel durability from 128 to something else :)

**Comment by jusipat** [comment]
Hi, if I am understanding this correctly you are asking to change the trowellable block from regular stone to stone bricks?
And for Trowel durability, recent updates have introduced more trowels with varying durabilities.

**Comment by superon** [comment]
sounds right, i am running the 1.16.5 version so doubt this'll be useful for me but pretty sure it would be for others

**Comment by jusipat** [comment]
There will be a backport done to 1.16.5 with all updated features and bug fixes coming as soon as it's done, which should be soon! As for changing the trowellable block, stone was chosen to be trowellable over stone bricks because the textures for stone bricks and stone castle bricks are similar and trowelling a large number of them at once may be frustrating. Though I may add a config file soon to change various settings in regards to this, it sadly wont happen anytime soon.

**Comment by superon** [comment]
oh ay, i can see that it makes sense from that pov.
just loving options, thinking not much about it i can see this would be an issue for worlds that don't have stone for whatever reason and we all know textures can be changed on a whim :)  i really do like the idea of the main mechanic here but for my use i'd want to use a custom block and custom item/durability.
been working on this pack for years so i can wait 
stay super

**Comment by jusipat** [comment]
1.16.5 backport is up on the Curseforge page!

**Comment by superon** [comment]
thanks, i just dl'd it and checked it out, can't work out how to change the blocks type with this version or the trowel durability from looking at the files in data after having unarchived it. is there supposed to be a config for this version?
also tried with modmenu

**Comment by jusipat** [comment]
Sorry, but the a config option was not included in this backport. Best that could be done for now is using the different Trowel varieties for different durability. The same goes for changing the castle block types.
